name: ass1
on: [push, pull_request]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install gitleaks
      run: |
         wget -q -O gitleaks.tar.gz https://github.com/gitleaks/gitleaks/releases/download/v8.18.0/gitleaks_8.18.0_linux_x64.tar.gz
         ls -l
         tar -xzvf gitleaks.tar.gz
         chmod +x gitleaks
         sudo mv gitleaks /usr/local/bin
    - name: run Gitleaks
      run: |
         gitleaks detect --redact
       
   
